config/routes.rb
Rails.application.routes.draw do
  get 'all_projects/index'
  #  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, 
  # see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/issues", to: "issues#index"
  get "/issues/:id", to: "issues#show" #:id gets put in the params hash
  resources :issues
  # get "/projects", to: "projects#index"
  # get "projects/report", to: "projects#report"
  get "/users", to: "users#index"
  get "/users/:id", to: "users#show" 
  get "/about", to: "abouts#index"
  # get "/about", to: redirect("/about.html.erb")
  get "/comments", to: "comments#index"
  get "/comments/:id", to: "comments#show"
  get "/project_reports", to: "project_reports#index"

  resources :users
  resources :projects do
    resources :issues do
      resources :comments
    end
  end
  post "projects/new", to: "projects#create"
  # "creates seven different routes in your application"
  # https://guides.rubyonrails.org/routing.html
  # post "/issues/new", to: "issues#create" #create
  post "/comments", to: "comments#create" #create
  post "/", to: "home#create"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # user ||= User.new 

    # guest user (not logged in)
    # can read Issues, Project and Comments
    can :read, Issue
    can :read, Project
    can :read, Comment

    if user != nil
      if user.role == "project_manager"
        # can do everything to everything
        can :manage, :all
      elsif user.role == "developer"
        can [:read, :update, :create], [Issue, Comment]
      else # end_user
        can [:create, :read], [Issue, Comment]
      end
    else # no user
      # p
      # p "user is nil"
      # p
      can :read, [Issue, Comment]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :issues, optional: true
    belongs_to :users, optional: true
    # these 'optional: true's are necceasary to avoid
    # 'ActiveRecord::RecordInvalid: Validation failed: Issues must exist, Users must exist'
    # errors. See https://stackoverflow.com/questions/38983666/validation-failed-class-must-exist
    validates :content, presence: true
end

app/models/issue.rb
class Issue < ApplicationRecord
    has_and_belongs_to_many :users, :dependent => :destroy
    # has_and_belongs_to_many :users
    # has_many :comments, :dependent => :destroy, foreign_key: :issue_id 
    has_many :comments 

    # belongs_to :projects
    belongs_to :projects, optional: true
    # 'optional: true' prevents the error
    # ActiveRecord::RecordInvalid: Validation failed: Projects must exist
    # when running rake db:seed

    validates :summary, presence: true
    validates :description, presence: true
    validates :status, presence: true
end

app/models/project.rb
require_relative './application_record'
class Project < ApplicationRecord
    has_many :issues#, :dependent => :destroy 
    #this is no longer needed because we do it manually.
    
    validates :summary, presence: true
    validates :description, presence: true
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_and_belongs_to_many :issues
    has_many :comments
    validates :role, presence: true
    # validates :username, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource :comment
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    # creat a new comment with info from the params hash
    Comment.create!(issue_id: params[:issue_id], 
                    user_id: params[:user_id],
                    content: params[:content])
    # Go to the comments index if something goes wrong
    redirect_back(fallback_location: comments_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @issues = Issue.all
    # p @user
  end

  def create
    # Here we must associate a user with a issue through the
    # join table by adding the user id and issue id to it
    # user = User.find(params[:user_id])
    # issue = Issue.find(params[:issue.id])
    User.find_by_username(params[:username]).issues << Issue.find_by_summary(params[:summary])
    # if User.ids.include?(params[:user_id].to_i) and Issue.ids.include?(params[:issue_id].to_i)
    #   User.find(params[:user_id]).issues << Issue.find(params[:issue_id])
    # else
      
    # end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # Authorize all actions for issue
  load_and_authorize_resource :issue

  def index
    @issues = Issue.all
  end

  def show
    @issue = Issue.find(params[:id])
  end

  # https://github.com/ryanb/cancan/issues/835#issuecomment-18663815
  # def issue_params
  #   params.require(:issue).permit(:summary, :description, :status)
  # end

  def create
    # create issues and attach them to the project found by title
    # Project.find_by_title(params{issue: {summary: "text", status: "text", description: "text"}}
    Project.find_by_title(params[:title]).issues.create!(
      summary: params[:summary], 
      description: params[:description],
      status: params[:status])

    # Project.find_by_title(params[:title]).issues.create!(issue_params)
    # Project.find_by_title(params[:title]).issues.create!(
    #                                       summary: params[:summary], 
    #                                       description: params[:description], 
    #                                       status: params[:status])
    redirect_to issues_url
  end

  def destroy
    @issue = Issue.find(params[:id])
    # first we must destroy any associated comments
    @issue.comments.each do |comment|
      comment.destroy
    end
    # Then we can destroy our isssue which no longer has comments
    @issue.destroy
    redirect_back fallback_location: '/'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource :project

  # https://github.com/ryanb/cancan/issues/835#issuecomment-18663815
  def project_params
    params.require(:project).permit(:summary, :description, :title)
  end

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    # We can't delete the project without deleting it's children and their children
    # First delete the grandkids: comments
    @project.issues.each do |issue|
      issue.comments.each do |comment|
        comment.destroy
      end
    end
    # then delete the kids: issues
    @project.issues.each do|issue|
      issue.destroy
    end
    @project.destroy
    redirect_back fallback_location: '/'
  end

  def create 
    project = Project.create!(title: params[:project][:title],
    summary: params[:project][:summary], 
    description: params[:project][:description],
    status: params[:project][:status])
    redirect_to projects_path(project)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def login
  end

  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    
    # credit https://levelup.gitconnected.com/simple-authentication-guide-with-ruby-on-rails-16a6255f0be8
    @user = User.create(params.require(:user).permit(:username, :password))
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/all_projects_helper.rb
module AllProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/project_reports_helper.rb
module ProjectReportsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<!DOCTYPE html>
<html>
    <head>
    
    </head>
    <body>
        <%= render "shared/menu" %>
        <h1>Comments#index</h1>
        <p>Find me in app/views/comments/index.html.erb</p>

        <ul>
            <% @comments.each do |comment| %>
                <li>
                    <h3><%= link_to comment.content, {controller: "issues", 
                                                    action: "show",
                                                    id: comment.issue_id} %></h3>
                </li>
            <% end %>
        </ul>
    </body>
</html>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/issues/index.html.erb
<!DOCTYPE html>
<html>
    <head> 
    </head>
    <body>

        <%= render "shared/menu" %>
        <h2 class="centered"> All Issues: </h2>
        <ul>
            <%#= Show all the issues, their statuses, summaries and comments%>
            <% @issues.each do |issue| %>
                <li>
                    <div class="card">
                        <div class="card-body">
                            <h2> Summary: <%= link_to issue.summary, issue_path(issue)  %> </h2>
                            <p> Description: <%= issue.description  %> </p>
                            <h3> Status: 
                            <% if issue.status.downcase == "unresolved" %>
                                <span class="red"><%= issue.status  %></span></h3>
                            <% else %>
                                <span class="green"><%= issue.status  %></span></h3>
                            <% end %>
                            <ul>
                                <li>
                                    <% issue.comments.each do |comment| %>
                                        <div class="card">
                                            <div class="card-body">
                                                <%= comment.content %>
                                            </div>
                                        </div>
                                    <% end %>
                                </li>
                            </ul>
                        </div>
                    </div>
                </li>
            <% end %>
        </ul>

        <div class="centered">
            <p>Issues#index</p>
            <p>Find me in app/views/issues/index.html.erb</p>
        </div>
    </body>
</html>

app/views/issues/show.html.erb
<!DOCTYPE html>
<html>
    <head>
    
    </head>
    <body>
        <%= render "shared/menu" %>
        <div class="centered">
            <%#= Show all info about an issue including comments%>
            <h3><%= @issue.summary%> Issue id: <%= @issue.id%> </h3>
            <p><%= @issue.description%><p>
            <% if @issue.status.downcase == "unresolved" %>
                <h5 class="red"><%= @issue.status%></h5>
            <% else %>
                <h5 class="green"><%= @issue.status%></h5>
            <% end %>
            <h4> Comments: </h4>
            <ul>
            <% @issue.comments.each do |comment|%>
                <li>
                    <div class="card centered-div">
                        <div class="card-body">
                            <p class="bold"> 
                                <% user = User.find(comment.user_id)%>
                                <p> user id: <%= comment.user_id %> </p>
                                <%= link_to user.username, user_path(user) %>:
                                <p><%= comment.content %></p>
                            </p>
                        </div>
                    </div>
                </li>
            <% end %>

            <%#= Create a comment on any issue given it's id %>
            <%= form_with model: @comment, :url => comments_url do |form| %>
                <p><%= form.label :New_comment %></p>

                <h5>User id: </h5>
                <p><%= form.text_area :user_id, size: "10x2" %></p>

                <h5>Issue id: </h5>
                <p><%= form.text_area :issue_id, size: "10x2" %></p>

                <h5>Content: </h5>
                <p><%= form.text_area :content, size: "20x3" %></p>

                <%= form.submit %>
            <% end %>
        </div>
    </body>
</html>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html>
    <head> 
    </head>

    <body>
        <%= render "shared/menu" %>
            <% if can? :manage, :all %>
                <br>
                <br>
                <p class="centered"> <%= link_to 'New Project', new_project_path, :class => "btn btn-success" %> </p>
                <p class="centered"> <%= link_to 'All Projects Report', all_projects_index_path, :class => "btn btn-warning" %> </p>
            <% end %>
            <h2 class="centered"> All Projects: </h2>
            <p class="centered"> -------------- </p>
            <% @projects.each do |project| %>
                <ul>
                    <div class="card centered-div">
                        <div class="card-body centered">
                            <li>
                                <h3><%= link_to project.title, project_path(project) %>: </h3>
                                <h4><%= project.summary%></h4>
                                <p><%= project.description %></p>
                                <ul>
                                    <h4>Issues:</h4>
                                    <% project.issues.each do |issue| %>
                                        <li> <%=  link_to issue.summary, issue_path(issue) %>
                                        </li>
                                    <% end %>
                                </ul>
                            </li>
                        </div>
                    
                    </div>
                </ul>
            <% end %>
            <p></p>
            <p class="centered">Projects#index</p>
            <p class="centered">Find me in app/views/projects/index.html.erb</p>

        </ul>
    </body>
</html>

app/views/projects/new.html.erb
<!DOCTYPE html>
<html>
    <head>
    
    </head>
    <body>
        <%= render "shared/menu" %>
        <div class="centered"> 
            <h2>New Project:</h2>
            <p>Description </p> 

            <%#= create a form for new projects %>
            <%= form_with model: @project do |form| %>
                <h3>Title: </h3>
                <p><%= form.text_area :title, size: "16x1" %></p>
                <h3>Summary: </h3>
                <p><%= form.text_area :summary, size: "20x2" %></p>
                <h3>Description:  </h3>
                <p><%= form.text_area :description, size: "25x5" %></p>

                 <p><%#= form.text_area :status, size: "16x1" %></p>

                <h3>Status: </h3>
                <% form.label "Status" %>
                <% statuses = ['complete', 'incomplete'] %>
                <p><%= form.select(:status, ['complete','incomplete']) %></p>
                <p><%#= form.select :status, statuses %></p>

                <p><%= form.submit "Submit" %></p>
            <% end %>

        </div>
    <body>
<html>

app/views/projects/show.html.erb
<!DOCTYPE html>
<html>
    <head>
    
    </head>
    <body>
        <%= render "shared/menu" %>
        <h2 class="centered" >Project: <%=  @project.title %> 
        <!-- The columns below are using Bootstrap: -->
        <div class="row"> 
            <div class="col-8"><span class="underlined"> Issues: </span>
                <ul class="no-bullets">
                    <% @project.issues.each do |issue| %>
                        <div class="card">
                            <li><div class="card-body">

                                <p><%= link_to issue.summary, issue_path(issue) %> - 
                                <% if issue.status %>
                                    <% if issue.status.downcase == "unresolved" %>
                                        <span class="red"><%= issue.status  %></span>
                                    <% else %>
                                        <span class="green"><%= issue.status  %></span>
                                    <% end %>

                                    <% issue.comments.each do |comment| %>
                                        <p><div class="bold">Username: <%= User.find(comment.user_id).username %>:</div> 
                                        <%= comment.content %></p>
                                    <% end %>
                                <% else %>
                                     <span class="orange">Warning: No Issue Status</span>
                                <% end %>
                            </div></li>
                        </div>
                    <% end %>
                </ul>
                
            </div>
            <div class="col-4">
                <% if @project.status %>
                    <% if @project.status.downcase == "complete" %>
                        <span class="green"><%= @project.status  %></span>
                    <% else %>
                        <span class="red"><%= @project.status  %></span>
                    <% end %>
                <% else %>
                    <span class="orange">Warning: No project status</span>
                <% end %>

                <p><%= button_to "Project Report", 
                    project_reports_path(@project), 
                    :method => :get
                %></p>
                <%= form_with model: @issue, :url => issues_path do |form| %>
                    <p><%= form.label :New_Issue %></p>
                    <h5>Project Title: </h5>
                    <!-- Create a new Issue -->
                    <!-- Create a dropdown of project titles -->
                    <% titles = [] %>
                    <% Project.all.each do |project| %>
                        <% titles << project.title%>
                    <% end %>
                    <p><%= form.select :title, titles %></p>  

                    <h5>Summary: </h5>
                    <p><%= form.text_area :summary, size: "15x3" %></p>
                    <h5>Description: </h5>
                    <p><%= form.text_area :description, size: "30x5" %></p>
                    <h5>Status: </h5>
                    <p><%= form.text_area :status, size: "10x2" %></p>
                    <%= form.submit %>
                <% end %>
            </div>

        </div>
    </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
    <head> 
    </head>
    <body>
        <%= render "shared/menu" %>

        <h1 class="centered"> Users: </h1>

        <ul>
            <% @users.each do |user| %>
                <li>
                    <div class="card">
                        <div class="card-body">
                            <h2> Username: <%= link_to user.username, user_path(user)  %> </h2>
                            <% if user.role == "project_manager"%>
                                <h3> Status: Project Manager </h3>
                            <% elsif  user.role == "developer"%>
                                <h3> Status: Developer </h3>
                            <% else #we assume user is an end user%> 
                                <h3> Status: End User </h3>
                            <% end %>

                            <% if !user.issues.empty?%>
                                <h4> Issues: </h4>
                            <% end %>
                            <% user.issues.each do |issue|%>
                                <%= issue.summary %>
                                <% if issue.status.downcase == "resolved"%>
                                    <p class="green"><%= issue.status %></p>
                                <% else %>
                                    <p class="red"><%= issue.status %></p>
                                <% end %>
                            <% end %>

                        </div>
                    </div>
                </li>
            <% end %>
        </ul>
        <div class="centered">
            <h1>users#index</h1>
            <p>Find me in app/views/users/index.html.erb</p>
        </div>
    <body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>


<% # credit https://levelup.gitconnected.com/simple-authentication-guide-with-ruby-on-rails-16a6255f0be8 %>
<%= form_for @user do |form|%>
    <%= form.label :username%><br>
    <%= form.text_field :username%><br>
    <%= form.label :password%><br>
    <%= form.password_field :password%><br>
    <%= form.submit %>
<%end%>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
    <head> 
    </head>
    <body>

        <%= render "shared/menu" %>
        <%#= render "shared/status", :user => @user %>

        <h1 class="centered"> User </h1>

        <div class="container">
            <div class="card">
                <h2> Username: <%= @user.username  %> </h2>
                <h3> Role: <%= @user.role  %> </h3>
            </div>

            <div class="card">
                <h4> Comments: </h4>
                <ul>
                    <% @user.comments.each do |comment| %>
                        <li>
                            <p>
                                <%= comment.content %>
                                <%#= link_to comment.content, issue_path(comment.issue_id) %>
                            </p>
                        </li>
                    <% end %>
                </ul>

                <h4> Issues: </h4>
                <ul>
                    <% @user.issues.each do |issue| %>
                        <li>
                            <p>  
                                <%= link_to issue.summary, issue_path(issue)%>
                            </p>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </body>
</html>