config/routes.rb
Rails.application.routes.draw do
  get 'all_projects/index'
  #  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, 
  # see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/issues", to: "issues#index"
  get "/issues/:id", to: "issues#show" #:id gets put in the params hash
  resources :issues
  # get "/projects", to: "projects#index"
  # get "projects/report", to: "projects#report"
  get "/users", to: "users#index"
  get "/users/:id", to: "users#show" 
  get "/about", to: "abouts#index"
  # get "/about", to: redirect("/about.html.erb")
  get "/comments", to: "comments#index"
  get "/comments/:id", to: "comments#show"
  get "/project_reports", to: "project_reports#index"

  resources :users
  resources :projects do
    resources :issues do
      resources :comments
    end
  end
  post "projects/new", to: "projects#create"
  # "creates seven different routes in your application"
  # https://guides.rubyonrails.org/routing.html
  # post "/issues/new", to: "issues#create" #create
  post "/comments", to: "comments#create" #create
  post "/", to: "home#create"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # user ||= User.new 

    # guest user (not logged in)
    # can read Issues, Project and Comments
    can :read, Issue
    can :read, Project
    can :read, Comment

    if user != nil
      if user.role == "project_manager"
        # can do everything to everything
        can :manage, :all
      elsif user.role == "developer"
        can [:read, :update, :create], [Issue, Comment]
      else # end_user
        can [:create, :read], [Issue, Comment]
      end
    else # no user
      # p
      # p "user is nil"
      # p
      can :read, [Issue, Comment]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :issues, optional: true
    belongs_to :users, optional: true
    # these 'optional: true's are necceasary to avoid
    # 'ActiveRecord::RecordInvalid: Validation failed: Issues must exist, Users must exist'
    # errors. See https://stackoverflow.com/questions/38983666/validation-failed-class-must-exist
    validates :content, presence: true
end

app/models/issue.rb
class Issue < ApplicationRecord
    has_and_belongs_to_many :users, :dependent => :destroy
    # has_and_belongs_to_many :users
    # has_many :comments, :dependent => :destroy, foreign_key: :issue_id 
    has_many :comments 

    # belongs_to :projects
    belongs_to :projects, optional: true
    # 'optional: true' prevents the error
    # ActiveRecord::RecordInvalid: Validation failed: Projects must exist
    # when running rake db:seed

    validates :summary, presence: true
    validates :description, presence: true
    validates :status, presence: true
end

app/models/project.rb
require_relative './application_record'
class Project < ApplicationRecord
    has_many :issues#, :dependent => :destroy 
    #this is no longer needed because we do it manually.
    
    validates :summary, presence: true
    validates :description, presence: true
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_and_belongs_to_many :issues
    has_many :comments
    validates :role, presence: true
    # validates :username, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource :comment
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    # creat a new comment with info from the params hash
    Comment.create!(issue_id: params[:issue_id], 
                    user_id: params[:user_id],
                    content: params[:content])
    # Go to the comments index if something goes wrong
    redirect_back(fallback_location: comments_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @issues = Issue.all
    # p @user
  end

  def create
    # Here we must associate a user with a issue through the
    # join table by adding the user id and issue id to it
    # user = User.find(params[:user_id])
    # issue = Issue.find(params[:issue.id])
    User.find_by_username(params[:username]).issues << Issue.find_by_summary(params[:summary])
    # if User.ids.include?(params[:user_id].to_i) and Issue.ids.include?(params[:issue_id].to_i)
    #   User.find(params[:user_id]).issues << Issue.find(params[:issue_id])
    # else
      
    # end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # Authorize all actions for issue
  load_and_authorize_resource :issue

  def index
    @issues = Issue.all
  end

  def show
    @issue = Issue.find(params[:id])
  end

  # https://github.com/ryanb/cancan/issues/835#issuecomment-18663815
  # def issue_params
  #   params.require(:issue).permit(:summary, :description, :status)
  # end

  def create
    # create issues and attach them to the project found by title
    # Project.find_by_title(params{issue: {summary: "text", status: "text", description: "text"}}
    Project.find_by_title(params[:title]).issues.create!(
      summary: params[:summary], 
      description: params[:description],
      status: params[:status])

    # Project.find_by_title(params[:title]).issues.create!(issue_params)
    # Project.find_by_title(params[:title]).issues.create!(
    #                                       summary: params[:summary], 
    #                                       description: params[:description], 
    #                                       status: params[:status])
    redirect_to issues_url
  end

  def destroy
    @issue = Issue.find(params[:id])
    # first we must destroy any associated comments
    @issue.comments.each do |comment|
      comment.destroy
    end
    # Then we can destroy our isssue which no longer has comments
    @issue.destroy
    redirect_back fallback_location: '/'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource :project

  # https://github.com/ryanb/cancan/issues/835#issuecomment-18663815
  def project_params
    params.require(:project).permit(:summary, :description, :title)
  end

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    # We can't delete the project without deleting it's children and their children
    # First delete the grandkids: comments
    @project.issues.each do |issue|
      issue.comments.each do |comment|
        comment.destroy
      end
    end
    # then delete the kids: issues
    @project.issues.each do|issue|
      issue.destroy
    end
    @project.destroy
    redirect_back fallback_location: '/'
  end

  def create 
    project = Project.create!(title: params[:project][:title],
    summary: params[:project][:summary], 
    description: params[:project][:description],
    status: params[:project][:status])
    redirect_to projects_path(project)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    
    # credit https://levelup.gitconnected.com/simple-authentication-guide-with-ruby-on-rails-16a6255f0be8
    @user = User.create(params.require(:user).permit(:username, :password))
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/all_projects_helper.rb
module AllProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/project_reports_helper.rb
module ProjectReportsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/index.html.erb
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <%= render "shared/menu" %>

        <div id="about">
            <div class="card">
                <div class="card-body">
                    <h1 id="About-header">What is an Issue Tracker?</h1>
                    <p id="About-text">Issue Tracker keeps track of issues for a given project. It allows end users to create issues, developers to create, respond, and update issues, 
                    and project managers to do all of the above as well as assign developers to certain issues. Issue tracking allows projects to be broken up into
                    manageable pieces. It tracks project completion.</p>
                </div>
            </div>
        </div>
        <p class="centered"> Abouts#index </p>
        <p class="centered"> Find me in app/views/abouts/index.html.erb</p>
    </body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
    <head> 
    </head>
    <body>
        <%= render "shared/menu" %>
        <div class="centered">

        <% if @user == nil %>
        <p><%= link_to "Login", new_user_session_path %> </p>
        <% elsif @user.role.downcase == "developer" || @user.role.downcase == "project_manager" %>
            <h2 class="underlined"> 
                <% if @user.role.downcase == "developer" %>
                    Developer Dashboard 
                <% elsif @user.role.downcase == "project_manager" %>
                    Project Manager Dashboard
                <% end %> </h2>
            
            <div class="container">
                <div class="row">

                    <div class=col-sm>
                        <% if @user.role.downcase == "project_manager" %>
                            <p><%= link_to 'New Project', new_project_path, :class => "btn btn-light"%> </p>
                        <% end %>
                        <h4 class="underlined">Projects </h4>
                        <ul>
                            <% Project.all.each do |project| %>
                                <li>
                                    <p>* <%= link_to project.title, project_path(project) %>
                                    <%# only show delete buttons to the project manager %>
                                    <% if  @user.role.downcase == "project_manager"%>
                                        <%# https://stackoverflow.com/questions/18723155/destroy-path-not-working-in-ruby-on-rails %>
                                        <%= link_to 'Delete project ' + project.id.to_s, project_path(project),  
                                            :class => "btn btn-danger",
                                            method: :delete, data: { confirm: "Are you sure?" } %> </p>
                                    <% end %>
                                </li>
                            <% end %>
                        </ul>
                        <%#= Make dropdowns for usernames to match with summaries%>
                        <%= form_with url: "/" do |form| %>
                            <h3>Assign a user to an issue: </h3>
                            <% usernames = [] %>
                            <% User.all.each do |user| %>
                                <% usernames << user.username%>
                            <% end %>
                            <p><%= form.select :username, usernames %></p>

                            <% summaries = [] %>
                            <% Issue.all.each do |issue| %>
                                <% summaries << issue.summary%>
                            <% end %>
                            <p><%= form.select :summary, summaries %></p>

                            <p><%= form.submit %></p>
                        <% end %></p>
                        <h4 class="underlined" ><%= link_to "Users", users_path%> </h4>
                        
                    </div>

                    <div class=col-sm>
                        <% if @user.role.downcase == "project_manager" %>
                            <p><%= link_to 'All Projects Report', all_projects_index_path, :class => "btn btn-light"%> </p>
                        <% end %>
                        <h4 class="underlined">Issues </h4>
                        <ul>
                            <% Issue.all.each do |issue| %>
                                <li class="card">
                                <p> * [<%= Project.find(issue.project_id).title%><%#= link_to Project.find(issue.project_id).title, 
                                               project_path(issue.project_id) %>] 
                                    <span> - </span>
                                    <%= link_to issue.summary, issue_path(issue) %>
                                    <%# only show delete buttons to the project manager %>
                                    <% if  @user.role.downcase == "project_manager"%>
                                        <%# https://stackoverflow.com/questions/18723155/destroy-path-not-working-in-ruby-on-rails %>
                                        <%= link_to 'Delete issue ' + issue.id.to_s, issue_path(issue),  
                                            :class => "btn btn-danger",
                                            method: :delete, data: { confirm: "Are you sure?" }  %> 
                                    <% end %>
                                </p>
                                </li>
                            <% end %>
                        </ul>
                    </div>

                </div>
            </div>

        <% elsif user_signed_in? %>
            <h2> End user dashboard </h2>
            <!-- display all issues associated with user -->
            <h4> User's issues: </h4>
            <ul>
                <% @issues.each do |issue| %>
                    <% issue.users.each do |user| %>
                        <% if user == @user %>
                            <li>
                                <%= link_to issue.summary, issue_path(issue) %>
                            </li>
                        <% end %>
                    <% end %>
                <% end %>
            </ul>
        <% end %>
        <div class="centered">Home#index</div>
        <div class="centered">Find me in app/views/home/index.html.erb</div>
    </body>
</html>